version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
      - '5001:5001'
    volumes:
      - .:/app
    entrypoint: ['/bin/bash', '/app/docker-entrypoint.sh']
    depends_on: []
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      LANG: 'C.UTF-8'
      RUNSERVER: '${RUNSERVER-True}'
      RUNTEST: '${RUNTEST-True}'